MYSQL_HOST = 'localhost:3307'
MYSQL_USER = 'root'
MTSQL_PASSWORD = 'root'
MYSQL_DATABASE = 'rafaelmagalhaes_db'
#PARA RODAR O PROJETO NAO POSSO ESQUECER DE DIGITAR O CODIGO ABAIXO NO CONSOLE(TELA DE EXECUÇÃO)
# pip install mysql-connector-python